config/routes.rb
Rails.application.routes.draw do

root 'static_pages#home'
get '/contact', to: 'static_pages#contact'
get '/revolution', to: 'static_pages#revolution'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/root_model_controller.rb
class RootModelController < ApplicationController
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
    def home
    end

    def contact
    end

    def revolution
    end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/root_model_helper.rb
module RootModelHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Joe Zagorski </title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/static_pages/contact.html.erb
<h1> Contact me via: </h1>

app/views/static_pages/home.html.erb
<!DOCTYPE html>
<html>
<title> Joe Zagorski </title>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link rel='stylesheet' href='https://fonts.googleapis.com/css?family=Roboto'>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<style>
html,body,h1,h2,h3,h4,h5,h6 {font-family: "Helvetica", sans-serif}
</style>
<body class="w3-light-grey">

<!-- Page Container -->
<div class="w3-content w3-margin-top" style="max-width:1400px;">

  <!-- The Grid -->
  <div class="w3-row-padding">
  
    <!-- Left Column -->
    <div class="w3-third">
    
      <div class="w3-white w3-text-grey w3-card-4">
        <div class="w3-display-container">
          <%= image_tag "old.png", :alt=> "me", :size => '100%' %> 
          <div class="w3-display-bottomleft w3-container w3-text-black">
          </div>
        </div>
        <div class="w3-container">
          <h2><i class="fa fa-address-book fa-fw w3-margin-right w3-large w3-text-teal"></i> Joe Zagorski </h2>
          <p><i class="fa fa-briefcase fa-fw w3-margin-right w3-large w3-text-teal"></i> Developer </p>
          <p><i class="fa fa-home fa-fw w3-margin-right w3-large w3-text-teal"></i> Cleveland, Ohio</p>
          <p><i class="fa fa-envelope fa-fw w3-margin-right w3-large w3-text-teal"></i> j.j.zagorski@gmail.com </p>
          <p><i class="fa fa-linkedin fa-fw w3-margin-right w3-large w3-text-teal"></i> <a href="http://www.linkedin.com/in/joe-zagorski-dev"> Connect with me on LinkedIn</a></p>
          <p><i class="fa fa-github fa-fw w3-margin-right w3-large w3-text-teal"></i> <a href="https://github.com/zagorski32611"> Check out my GitHub </a></p>

          <hr>

          <p class="w3-large"><b><i class="fa fa-asterisk fa-fw w3-margin-right w3-text-teal"></i>Skills</b></p>
          <p> The percentages indicate the proportion of time I've spent learning the technology </p>
          <p> Ruby on Rails </p>
          <div class="w3-light-grey w3-round-xlarge w3-small">
            <div class="w3-container w3-center w3-round-xlarge w3-teal" style="width:50%"> 50% </div>
          </div>
          <p> Ruby </p>
          <div class="w3-light-grey w3-round-xlarge w3-small">
            <div class="w3-container w3-center w3-round-xlarge w3-teal" style="width:30%">
              <div class="w3-center w3-text-white"> 30% </div>
            </div>
          </div>
          <p> Ubuntu (Server and Desktop) </p>
          <div class="w3-light-grey w3-round-xlarge w3-small">
            <div class="w3-container w3-center w3-round-xlarge w3-teal" style="width:10%"> 10% </div>
          </div>
          <p> Python </p>
          <div class="w3-light-grey w3-round-xlarge w3-small">
            <div class="w3-container w3-center w3-round-xlarge w3-teal" style="width:10%"> 10% </div>
          </div>
          <br>

          <p class="w3-large w3-text-theme"><b><i class="fa fa-globe fa-fw w3-margin-right w3-text-teal"></i>Languages</b></p>
          <p>English</p>
          <div class="w3-light-grey w3-round-xlarge">
            <div class="w3-round-xlarge w3-teal" style="height:24px;width:100%"></div>
          </div>

          <br>
        </div>
      </div><br>

    <!-- End Left Column -->
    </div>

    <!-- Right Column -->
    <div class="w3-twothird">
      <!-- Personal Projects -->
      <div class="w3-container w3-card w3-white">
        <h2 class="w3-text-grey w3-padding-16"><i class="fa fa-code fa-fw w3-margin-right w3-xxlarge w3-text-teal"></i> Projects </h2>
        <div class="w3-container">
          <h5 class="w3-opacity"><b> Sentinel.py </b></h5>
            <p> 
              This is a Python Script that monitors 2 production servers. It creates an SSH connection once per hour, runs the df -h command to get the usage 
              levels of each disk on the server. It receives the data as bytes, converts it to a string, parses the string to a multidimensional array, and if the usage 
              level is above a threshold, sends a text message to myself and two developers. 
            </p>
            <p>
              Available in two flavors:
              <ul>
                <li> Ruby </li>
                <li> Python </li>
              </ul>
            </p>
          <hr>
        </div>

        <div class="w3-container">
          <h5 class="w3-opacity"><b>DMS </b></h5>
          <p>
            This is a web application used to replace CDK, a command-line based software commonly used in the industry. It has a graphical user interface 
            (built on Twitter’s Bootstrap CSS), uses color-coding and basic search functionality to help dealerships reduce paper and streamline their workflows for 
            service and parts departments. Built with Ruby On Rails 5.0, SQLite with custom association tables for repair orders, customers and employees, 
            Twitter’s Bootstrap CSS and Heroku for deployment. 
            # Note, this app is under developement, stay tuned for changes! 
            Check it out here:
            <a href= "https://github.com/zagorski32611/DMS" target="_blank"><%= image_tag "GitHub.png"%></a>
          </p>
          <hr>
        </div>

        <div class="w3-container">
          <h5 class="w3-opacity"><b> Home Lab </b></h5>
          <p>
            I use an old Dell 1950 Poweredge Server, running Ubuntu Server 16.04, to create a home SSH server. 
            It holds backups of my two Ubuntu laptops and one Ubuntu Desktop and one Windows 10 laptop
          </p>
          <br>
        </div>

        <div class="w3-container">
          <h5 class="w3-opacity"><b> Revolution Gymnastic </b></h5>
          <p>
            This is a contract from Fiverr.com. I was tasked with building a Rails site that allowed the owner of a gymnastics school (in the UK) to log in and add courses and parents.
            The parents can log into the site and add their child or children. Then, the parent can enroll those children in to courses listed. 
            The app will save the student and course into an association table, then display that association table to the owner of the school. 
            I can't show you the entire app, however, I can show you some really interesting custom methods I wrote to calcualte the student's tuition, the view before_action method to only show students of the logged in parent and more!
            <%= link_to "Check it out!", revolution_path %>

          </p>
          <br>
        </div>

        <div class="w3-container">
          <h5 class="w3-opacity"><b> This Web Site!  </b></h5>
          <p>
            I built this website as a way to showcase my HTML / CSS abilities (which are somewhat limited), some very basic ruby on rails development, and my sysadmin aspirations as well. 
            This site was origianlly planned to be built on my own Linode Server using Passenger, Nginx and Rails. Some very confusing technical difficulties forced me to switch over to Heroku. 
            In the near future, I WILL build my own custom stack. Stay tuned!
            Check it out on GitHib!
            <a href="https://github.com/zagorski32611/personal_site" target="_blank"><%= image_tag "GitHub.png"%></a>
          </p>
          <br>
        </div>
      </div>
    
      <!-- Work Experience -->

      <div class="w3-container w3-card w3-white w3-margin-bottom">
        <h2 class="w3-text-grey w3-padding-16"><i class="fa fa-suitcase fa-fw w3-margin-right w3-xxlarge w3-text-teal"></i>Work Experience</h2>
        <div class="w3-container">
          <h5 class="w3-opacity"><b> Customer Support Specialist  </b></h5>
          <h6 class="w3-text-teal"><i class="fa fa-calendar fa-fw w3-margin-right"></i> June 2017 - <span class="w3-tag w3-teal w3-round">Current</span></h6>
          <p>
            <ul> 
              <li> Provided level 1 tech support for the company’s proprietary software </li> 
              <li> Provided training to new and existing clients </li>
              <li> Reported weekly on customer service KPI’s including support ticket counts and statuses </li>
              <li> Created a web app to allow managers to view up-to-the-minute information </li>
              <li> Created forms using HTML, CSS and PHP Elements </li>
              <li> Wrote a monitoring program that SSHs into each production server and alerts us if it’s too full or down. </li>
              <li> Established a process to onboard new clients </li>
            </ul>
          </p>
          <hr>
        </div>
        <div class="w3-container">
          <h5 class="w3-opacity"><b> Anti Money Laundering Investigator </b></h5>
          <h6 class="w3-text-teal"><i class="fa fa-calendar fa-fw w3-margin-right"></i>May 2016 - December 2016 </h6>
          <p>
            <ul>
              <li> Conducted investigations for possible money laundering or terrorist financing </li>
              <li> Used many different internal and external systems to find information about the clients and their transactional activity </li>
              <li> Worked with KeyBank fraud investigators, OFAC specialists and EDD analysts  </li>
              <li> Conducted investigations initiated as a result of a subpoena and contacted local and federal law enforcement  </li>
              <li> Filed Suspicious Activity Reports for numerous types of suspicious activity including elder abuse, EFT/wire transfers, structuring, unknown source of funds </li>
            </ul>
          </p>
          <hr>
        </div>
      </div>

      <!-- Education -->
      <div class="w3-container w3-card w3-white">
        <h2 class="w3-text-grey w3-padding-16"><i class="fa fa-certificate fa-fw w3-margin-right w3-xxlarge w3-text-teal"></i> Education </h2>
        <div class="w3-container">
          <h5 class="w3-opacity"><b> Cleveland State University </b></h5>
          <h6 class="w3-text-teal"><i class="fa fa-calendar fa-fw w3-margin-right"></i> April 2009 to May 2014 </h6>
          <p> Major: Economics </p>
          <p> Minor: Operations and Supply Chain Management </p>
          <hr>
        </div>
      </div>

    <!-- End Right Column -->
    </div>
    
  <!-- End Grid -->
  </div>
  
  <!-- End Page Container -->
</div>

<footer class="w3-container w3-teal w3-center w3-margin-top">

</footer>

</body>
</html>

app/views/static_pages/revolution.html.erb
<!DOCTYPE html>
<html>
<title> Joe Zagorski </title>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link rel='stylesheet' href='https://fonts.googleapis.com/css?family=Roboto'>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<style>
html,body,h1,h2,h3,h4,h5,h6 {font-family: "Helvetica", sans-serif}
</style>
<body class="w3-light-grey">

<!-- Page Container -->
<div class="w3-content w3-margin-top" style="max-width:1400px;">

  <!-- The Grid -->
  <div class="w3-row-padding">
  
    <!-- Left Column -->
    <div class="w3-third">
    
    <div class="w3-white w3-text-grey w3-card-4">
        <div class="w3-display-container">
          <%= image_tag "old.png" %>
          <div class="w3-display-bottomleft w3-container w3-text-black">
          </div>
        </div>
        <div class="w3-container">
          <h2><i class="fa fa-address-book fa-fw w3-margin-right w3-large w3-text-teal"></i> Joe Zagorski </h2>
          <p><i class="fa fa-briefcase fa-fw w3-margin-right w3-large w3-text-teal"></i> Developer </p>
          <p><i class="fa fa-home fa-fw w3-margin-right w3-large w3-text-teal"></i> Cleveland, Ohio</p>
          <p><i class="fa fa-envelope fa-fw w3-margin-right w3-large w3-text-teal"></i> j.j.zagorski@gmail.com </p>
          <hr>

          <p class="w3-large"><b><i class="fa fa-asterisk fa-fw w3-margin-right w3-text-teal"></i>Skills</b></p>
          <p> The percentages indicate the proportion of time I've spent learning the technology </p>
          <p> Ruby on Rails </p>
          <div class="w3-light-grey w3-round-xlarge w3-small">
            <div class="w3-container w3-center w3-round-xlarge w3-teal" style="width:90%"> 50% </div>
          </div>
          <p> Ruby </p>
          <div class="w3-light-grey w3-round-xlarge w3-small">
            <div class="w3-container w3-center w3-round-xlarge w3-teal" style="width:80%">
              <div class="w3-center w3-text-white"> 30% </div>
            </div>
          </div>
          <p> Ubuntu (Server and Desktop) </p>
          <div class="w3-light-grey w3-round-xlarge w3-small">
            <div class="w3-container w3-center w3-round-xlarge w3-teal" style="width:75%"> 10% </div>
          </div>
          <p> Python </p>
          <div class="w3-light-grey w3-round-xlarge w3-small">
            <div class="w3-container w3-center w3-round-xlarge w3-teal" style="width:50%"> 10% </div>
          </div>
          <br>

          <p class="w3-large w3-text-theme"><b><i class="fa fa-globe fa-fw w3-margin-right w3-text-teal"></i>Languages</b></p>
          <p>English</p>
          <div class="w3-light-grey w3-round-xlarge">
            <div class="w3-round-xlarge w3-teal" style="height:24px;width:100%"></div>
          </div>

          <br>
      </div><br>
    <!-- End Left Column -->
    </div>
    </div>
    <!-- Right Column -->
    <div class="w3-twothird">
      <!-- Title  -->
      <div class="w3-container w3-card w3-white">
        <div class="w3-container">
          <h5 class="w3-opacity"><b> Revolution Gymnastic Custom Methods </b></h5>
            <p> 
              I had a great deal of fun building this app! I learned a great deal about adding my own logic. If you're not familiar, Ruby on Rails has "helper methods" that allow you to keep logic out of the views (among other things).
              Some of these methods helped me create this app. The goal here is to give you a brief idea of what I built:

            </p>
          <hr>
        </div>
  
        <div class="w3-container">
          <h5 class="w3-opacity"><b> Join Table </b></h5>
            <p> 
              So, the owner of the site (admin) can give parents a username and password. And parents can add their student(s). I used a controller method to make sure
              that parents can only see their students. The admin, however, can see all students. 
              </br>
              Additionally, a parent can enroll their student(s) in one or more courses. The mechanics behind this functionality work like so: 
              </br>
              I created a table that saves the student id and the course id called enrollments.
            </p>
          <hr>
        </div>

        <div class="w3-container">
          <h5 class="w3-opacity"><b> Helper Methods </b></h5>
            <p> 
               The enrollments table only saves the student id and the course id. It's not very helpful! 
               So, I wrote a method that for each student id, queires the database and 'plucks' the student's first_name (pluck is a method for ActiveRecord, Rails' ORM)
               This also happens for the course as well. When the enrollments index view loads, the helper methods are called and return the student name and the course title: 
            </p>
            <code>
                def pluck_name(stid)</br>
                    @name = Student.where(id: stid).pluck(:first_name)</br>
                    return @name[0]</br>
                end</br>

                def pluck_course(cid)</br>
                    @title = Course.where(id: cid).pluck(:title)</br>
                    return @title[0]</br>
                end</br>
            </code>
          <hr>
        </div>